---
- hosts: all:!control
  become: true

  tasks:
    - name: Upgrade all packages, excluding kernel
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      when: ansible_distribution_version == "7.9" and ansible_distribution == "CentOS"
      

    - name: Reboot the server (if kernel update is installed)
      reboot:
        reboot_timeout: 3600
      
...
