---
- hosts: centos7  # This targets centos7 hosts in your inventory
  become: true  # Requires root privileges

  tasks:
    - name: Upgrade all packages, excluding kernel & foo related packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      when: ansible_distribution_version == "7.9" and ansible_distribution == "CentOS"
      

    - name: Reboot the server (if kernel update is installed)
      reboot:
        reboot_timeout: 3600 # Optional: Wait x seconds after reboot
      
...
